sudo: required
dist: jammy
addons:
  chrome: stable
  firefox: latest
language: node_js
services:
- xvfb
node_js:
- node
cache:
- node_modules
before_install:
- export NG_CLI_ANALYTICS=ci
install:
- npm install
script:
- npm run build-ckeditor && npm run lint && npm run coverage && ng e2e && cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
